///////////////////////////////////////////////////////////
//  Black.cs
//  Implementation of the Class Black
//  Generated by Enterprise Architect
//  Created on:      26-jun.-2022 14:42:02
//  Original author: Lenovo
///////////////////////////////////////////////////////////




using entidad;
namespace entidad {
	public class Black : Tarjeta {

		private Float SaldoUSD;

		public Black(){

		}

		~Black(){

		}

		public float CalcularGastoAdministrativo(){

			return 0;
		}

		public float ImpactarMiovimiento(){

			return 0;
		}

	}//end Black

}//end namespace entidad