///////////////////////////////////////////////////////////
//  Cliente.cs
//  Implementation of the Class Cliente
//  Generated by Enterprise Architect
//  Created on:      26-jun.-2022 14:42:03
///////////////////////////////////////////////////////////




using entidad;
namespace entidad {
	public class Cliente {

		private string Nombre;
		private string Apellido;
		private string Dni;
		private string Rol;
		public entidad.Tarjeta m_Tarjeta;

		public Cliente(){

		}

		~Cliente(){

		}

	}//end Cliente

}//end namespace entidad