///////////////////////////////////////////////////////////
//  Deposito.cs
//  Implementation of the Class Deposito
//  Generated by Enterprise Architect
//  Created on:      26-jun.-2022 14:42:03
//  Original author: Lenovo
///////////////////////////////////////////////////////////




using entidad;
namespace entidad {
	public class Deposito : Movimiento {

		public Deposito(){

		}

		~Deposito(){

		}

        public override void actualizarImpuesto(float monto)
        {
        
        }
    }//end Deposito

}//end namespace entidad