///////////////////////////////////////////////////////////
//  Movimiento.cs
//  Implementation of the Class Movimiento
//  Generated by Enterprise Architect
//  Created on:      26-jun.-2022 14:42:03
//  Original author: Lenovo
///////////////////////////////////////////////////////////




using entidad;
namespace entidad {
	public abstract class Movimiento {

		public float Impuesto;
		public string Moneda;
		public float Monto;
		public string Concepto;
		public entidad.Tarjeta m_Tarjeta;

        

        ~Movimiento(){

		}

		public abstract void actualizarImpuesto(float monto);

	}//end Movimiento

}//end namespace entidad