///////////////////////////////////////////////////////////
//  Movimiento.cs
//  Implementation of the Class Movimiento
//  Generated by Enterprise Architect
//  Created on:      26-jun.-2022 14:42:03
//  Original author: Lenovo
///////////////////////////////////////////////////////////




using entidad;
namespace entidad {
	public abstract class Movimiento {

		private float Impuesto;
		private string Moneda;
		private float Monto;
		public entidad.Tarjeta m_Tarjeta;

		public Movimiento(){

		}

		~Movimiento(){

		}

	}//end Movimiento

}//end namespace entidad