///////////////////////////////////////////////////////////
//  Pago.cs
//  Implementation of the Class Pago
//  Generated by Enterprise Architect
//  Created on:      26-jun.-2022 14:42:03
///////////////////////////////////////////////////////////




using entidad;
namespace entidad {
	public class Pago : Movimiento {

		public Pago(){

		}

		~Pago(){

		}

	}//end Pago

}//end namespace entidad