///////////////////////////////////////////////////////////
//  Pago.cs
//  Implementation of the Class Pago
//  Generated by Enterprise Architect
//  Created on:      26-jun.-2022 14:42:03
///////////////////////////////////////////////////////////

namespace entidad
{
    public class Pago : Movimiento
    {

        public Pago()
        {

        }

        ~Pago()
        {

        }

        public override void actualizarImpuesto(float monto)
        {
            Impuesto = (float)(monto * 0.05);
        }


    }//end Pago

}//end namespace entidad