///////////////////////////////////////////////////////////
//  Platinium.cs
//  Implementation of the Class Platinium
//  Generated by Enterprise Architect
//  Created on:      26-jun.-2022 14:42:03
//  Original author: Lenovo
///////////////////////////////////////////////////////////




using entidad;
namespace entidad {
	public class Platinium : Tarjeta {

		public Platinium(string numeroTarjeta, float saldoPesos, float limite)
		{
			NumeroTarjeta = numeroTarjeta;
			Categoria = "Platinum";
			SaldoPesos = saldoPesos;
			Limite = limite;
			

		}

		~Platinium(){

		}

		public float CalcularGastoAdministrativo(){

			return 0;
		}

		public float ImpactarMiovimiento(){

			return 0;
		}

	}//end Platinium

}//end namespace entidad