///////////////////////////////////////////////////////////
//  Platinium.cs
//  Implementation of the Class Platinium
//  Generated by Enterprise Architect
//  Created on:      26-jun.-2022 14:42:03
//  Original author: Lenovo
///////////////////////////////////////////////////////////

namespace entidad
{
    public class Platinium : Tarjeta
    {

        public Platinium(string numeroTarjeta, float saldoPesos, float limite)
        {
            NumeroTarjeta = numeroTarjeta;
            Categoria = "Platinum";
            SaldoPesos = saldoPesos;
            LimitePesos = limite;


        }

        ~Platinium()
        {

        }

        public float CalcularGastoAdministrativo()
        {

            return 0;
        }

        public override float CalcularGastoAdministrativo(float monto)
        {
            if (SaldoPesos >= 0)
            {
                return (float)(monto * 0.1);
            }
            else
            {
                return (float)(monto * 0.2);
            }
        }

        public float ImpactarMiovimiento()
        {

            return 0;
        }

        public override string Tipo()
        {
            return Categoria;

        }
    }//end Platinium

}//end namespace entidad