///////////////////////////////////////////////////////////
//  Tarjeta.cs
//  Implementation of the Class Tarjeta
//  Generated by Enterprise Architect
//  Created on:      26-jun.-2022 14:42:03
///////////////////////////////////////////////////////////




namespace entidad {
	public abstract class Tarjeta {

		protected string NumeroTarjeta;
		protected string Categoria;
		protected float SaldoPesos;
		protected float Limite;

      

        ~Tarjeta(){

		}

		public float CalcularGastoAdministrativo(){

			return 0;
		}

		public float ImpactarMiovimiento(){

			return 0;
		}

	}//end Tarjeta

}//end namespace entidad