///////////////////////////////////////////////////////////
//  Tarjeta.cs
//  Implementation of the Class Tarjeta
//  Generated by Enterprise Architect
//  Created on:      26-jun.-2022 14:42:03
///////////////////////////////////////////////////////////




namespace entidad {
	public abstract class Tarjeta {

		private int NumeroTarjeta;
		private string Categoria;
		private float SaldoPesos;
		private float Limite;

		public Tarjeta(){

		}

		~Tarjeta(){

		}

		public float CalcularGastoAdministrativo(){

			return 0;
		}

		public float ImpactarMiovimiento(){

			return 0;
		}

	}//end Tarjeta

}//end namespace entidad